// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaAuthUserSocial = "sca_auth_user_social"

// ScaAuthUserSocial mapped from table <sca_auth_user_social>
type ScaAuthUserSocial struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID;primary_key" json:"id,string"` // 主键ID
	UserID    string         `gorm:"column:user_id;type:varchar(50);not null;comment:用户ID" json:"user_id"`                              // 用户ID
	OpenID    string         `gorm:"column:open_id;type:varchar(50);not null;comment:第三方用户的 open id" json:"open_id"`                    // 第三方用户的 open id
	Source    string         `gorm:"column:source;type:varchar(10);comment:第三方用户来源" json:"source"`                                      // 第三方用户来源
	Status    int64          `gorm:"column:status;type:bigint(20);comment:状态 0正常 1 封禁" json:"status"`                                   // 状态 0正常 1 封禁
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;autoCreateTime;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;autoUpdateTime;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                   // 删除时间
}

// TableName ScaAuthUserSocial's table name
func (*ScaAuthUserSocial) TableName() string {
	return TableNameScaAuthUserSocial
}
