// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaStorageTagInfo = "sca_storage_tag_info"

// ScaStorageTagInfo mapped from table <sca_storage_tag_info>
type ScaStorageTagInfo struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键;primary_key" json:"id,string"` // 主键
	TagName   string         `gorm:"column:tag_name;type:varchar(50);not null;comment:标签名称" json:"tag_name"`                          // 标签名称
	TagKey    string         `gorm:"column:tag_key;type:varchar(50);comment:标签关键字" json:"tag_key"`                                    // 标签关键字
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;autoCreateTime;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;autoUpdateTime;comment:更新时间" json:"updated_at"`                  // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName ScaStorageTagInfo's table name
func (*ScaStorageTagInfo) TableName() string {
	return TableNameScaStorageTagInfo
}
