// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaUserFollow = "sca_user_follows"

// ScaUserFollow 用户关注表
type ScaUserFollow struct {
	FollowerID string         `gorm:"column:follower_id;type:varchar(50);not null;comment:关注者" json:"follower_id"`                              // 关注者
	FolloweeID string         `gorm:"column:followee_id;type:varchar(50);not null;comment:被关注者" json:"followee_id"`                             // 被关注者
	Status     int64          `gorm:"column:status;type:tinyint(3) unsigned;not null;comment:关注状态（0 未互关 1 互关）" json:"status"`                   // 关注状态（0 未互关 1 互关）
	CreatedAt  *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	ID         int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;primary_key" json:"id,string"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"` // 删除时间
}

// TableName ScaUserFollow's table name
func (*ScaUserFollow) TableName() string {
	return TableNameScaUserFollow
}
