// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaStorageTag = "sca_storage_tag"

// ScaStorageTag 标签表
type ScaStorageTag struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键;primary_key" json:"id,string"` // 主键
	FileID    int64          `gorm:"column:file_id;type:bigint(20);comment:文件ID" json:"file_id"`                                      // 文件ID
	TagID     int64          `gorm:"column:tag_id;type:bigint(20);comment:标签ID" json:"tag_id"`                                        // 标签ID
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;autoCreateTime;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;autoUpdateTime;comment:更新时间" json:"updated_at"`                  // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName ScaStorageTag's table name
func (*ScaStorageTag) TableName() string {
	return TableNameScaStorageTag
}
