version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --mem-queue-size=0 -data-path=/data --broadcast-address=1.95.0.111 --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    volumes:
      - ./nsqd/data:/data
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
