// Code generated by ent, DO NOT EDIT.

package scacommentlikes

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the scacommentlikes type in the database.
	Label = "sca_comment_likes"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTopicID holds the string denoting the topic_id field in the database.
	FieldTopicID = "topic_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCommentID holds the string denoting the comment_id field in the database.
	FieldCommentID = "comment_id"
	// FieldLikeTime holds the string denoting the like_time field in the database.
	FieldLikeTime = "like_time"
	// Table holds the table name of the scacommentlikes in the database.
	Table = "sca_comment_likes"
)

// Columns holds all SQL columns for scacommentlikes fields.
var Columns = []string{
	FieldID,
	FieldTopicID,
	FieldUserID,
	FieldCommentID,
	FieldLikeTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLikeTime holds the default value on creation for the "like_time" field.
	DefaultLikeTime func() time.Time
)

// OrderOption defines the ordering options for the ScaCommentLikes queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTopicID orders the results by the topic_id field.
func ByTopicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopicID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCommentID orders the results by the comment_id field.
func ByCommentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentID, opts...).ToFunc()
}

// ByLikeTime orders the results by the like_time field.
func ByLikeTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikeTime, opts...).ToFunc()
}
