// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaFileFolder = "sca_file_folder"

// ScaFileFolder mapped from table <sca_file_folder>
type ScaFileFolder struct {
	ID             int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`                         // 主键
	FolderName     string         `gorm:"column:folder_name;type:varchar(512);comment:文件夹名称" json:"folder_name"`                                   // 文件夹名称
	ParentFolderID int64          `gorm:"column:parent_folder_id;type:bigint;comment:父文件夹编号" json:"parent_folder_id"`                              // 父文件夹编号
	FolderAddr     string         `gorm:"column:folder_addr;type:varchar(1024);comment:文件夹名称" json:"folder_addr"`                                  // 文件夹名称
	UserID         string         `gorm:"column:user_id;type:varchar(20);comment:用户编号" json:"user_id"`                                             // 用户编号
	FolderSource   int64          `gorm:"column:folder_source;type:int;comment:文件夹来源 0相册 1 评论" json:"folder_source"`                               // 文件夹来源 0相册 1 评论
	CreatedAt      *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                          // 删除时间
}

// TableName ScaFileFolder's table name
func (*ScaFileFolder) TableName() string {
	return TableNameScaFileFolder
}
