// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScaUserMessage = "sca_user_message"

// ScaUserMessage mapped from table <sca_user_message>
type ScaUserMessage struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键;primary_key" json:"id,string"` // 主键
	TopicID   string         `gorm:"column:topic_id;type:varchar(50);comment:话题Id" json:"topic_id"`                               // 话题Id
	FromID    string         `gorm:"column:from_id;type:varchar(50);comment:来自人" json:"from_id"`                                  // 来自人
	ToID      string         `gorm:"column:to_id;type:varchar(50);comment:送达人" json:"to_id"`                                      // 送达人
	Content   string         `gorm:"column:content;type:text;comment:消息内容" json:"content"`                                        // 消息内容
	IsRead    int64          `gorm:"column:is_read;type:tinyint;comment:是否已读" json:"is_read"`                                     // 是否已读
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;autoCreateTime;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;autoUpdateTime;comment:更新时间" json:"updated_at"`              // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                             // 删除时间
}

// TableName ScaUserMessage's table name
func (*ScaUserMessage) TableName() string {
	return TableNameScaUserMessage
}
