// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aisvc.proto

package server

import (
	"context"

	"schisandra-album-cloud-microservices/app/aisvc/rpc/internal/logic/aiservice"
	"schisandra-album-cloud-microservices/app/aisvc/rpc/internal/svc"
	"schisandra-album-cloud-microservices/app/aisvc/rpc/pb"
)

type AiServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiServiceServer
}

func NewAiServiceServer(svcCtx *svc.ServiceContext) *AiServiceServer {
	return &AiServiceServer{
		svcCtx: svcCtx,
	}
}

// FaceRecognition
func (s *AiServiceServer) FaceRecognition(ctx context.Context, in *pb.FaceRecognitionRequest) (*pb.FaceRecognitionResponse, error) {
	l := aiservicelogic.NewFaceRecognitionLogic(ctx, s.svcCtx)
	return l.FaceRecognition(in)
}

// TfClassification
func (s *AiServiceServer) TfClassification(ctx context.Context, in *pb.TfClassificationRequest) (*pb.TfClassificationResponse, error) {
	l := aiservicelogic.NewTfClassificationLogic(ctx, s.svcCtx)
	return l.TfClassification(in)
}

// CaffeClassification
func (s *AiServiceServer) CaffeClassification(ctx context.Context, in *pb.CaffeClassificationRequest) (*pb.CaffeClassificationResponse, error) {
	l := aiservicelogic.NewCaffeClassificationLogic(ctx, s.svcCtx)
	return l.CaffeClassification(in)
}

// QueryFaceLibrary
func (s *AiServiceServer) QueryFaceLibrary(ctx context.Context, in *pb.QueryFaceLibraryRequest) (*pb.QueryFaceLibraryResponse, error) {
	l := aiservicelogic.NewQueryFaceLibraryLogic(ctx, s.svcCtx)
	return l.QueryFaceLibrary(in)
}

// ModifyFaceName
func (s *AiServiceServer) ModifyFaceName(ctx context.Context, in *pb.ModifyFaceNameRequest) (*pb.ModifyFaceNameResponse, error) {
	l := aiservicelogic.NewModifyFaceNameLogic(ctx, s.svcCtx)
	return l.ModifyFaceName(in)
}

// ModifyFaceType
func (s *AiServiceServer) ModifyFaceType(ctx context.Context, in *pb.ModifyFaceTypeRequest) (*pb.ModifyFaceTypeResponse, error) {
	l := aiservicelogic.NewModifyFaceTypeLogic(ctx, s.svcCtx)
	return l.ModifyFaceType(in)
}

// FuzzySearch
func (s *AiServiceServer) ImageClarity(ctx context.Context, in *pb.ImageClarityRequest) (*pb.ImageClarityResponse, error) {
	l := aiservicelogic.NewImageClarityLogic(ctx, s.svcCtx)
	return l.ImageClarity(in)
}
