// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type UploadRequest struct {
	Image       string `json:"image"`
	AccessToken string `json:"access_token"`
	UserId      string `json:"user_id"`
}
