[captcha]
verificationFailure = "verification failure!"

[login]
invalidAccount = "invalid account！"
notFoundAccount = "account not found！"
invalidPassword = "invalid password！"
loginFailed = "login failed！"
phoneFormatError = "phone number format error！"
captchaExpired = "captcha expired！"
captchaError = "captcha error！"
userNotRegistered = "user not registered！"
registerError = "register error！"
passwordNotMatch = "password not match！"
passwordFormatError = "password format error！"
resetPasswordError = "reset password error！"
loginSuccess = "login success！"
notPermission = "not permission！"
[sms]
smsSendTooFrequently = "sms send too frequently！"
smsSendFailed = "sms send failed！"
smsSendSuccess = "sms send success！"

[comment]
tooManyImages = "too many images！"
commentError = "comment error！"
LikeError = "like error！"
CancelLikeError = "cancel like error！"