// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aisvc.proto

package aiservice

import (
	"context"

	"schisandra-album-cloud-microservices/app/aisvc/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaffeClassificationRequest  = pb.CaffeClassificationRequest
	CaffeClassificationResponse = pb.CaffeClassificationResponse
	FaceLibrary                 = pb.FaceLibrary
	FaceRecognitionRequest      = pb.FaceRecognitionRequest
	FaceRecognitionResponse     = pb.FaceRecognitionResponse
	ImageClarityRequest         = pb.ImageClarityRequest
	ImageClarityResponse        = pb.ImageClarityResponse
	ModifyFaceNameRequest       = pb.ModifyFaceNameRequest
	ModifyFaceNameResponse      = pb.ModifyFaceNameResponse
	ModifyFaceTypeRequest       = pb.ModifyFaceTypeRequest
	ModifyFaceTypeResponse      = pb.ModifyFaceTypeResponse
	QueryFaceLibraryRequest     = pb.QueryFaceLibraryRequest
	QueryFaceLibraryResponse    = pb.QueryFaceLibraryResponse
	TfClassificationRequest     = pb.TfClassificationRequest
	TfClassificationResponse    = pb.TfClassificationResponse

	AiService interface {
		// FaceRecognition
		FaceRecognition(ctx context.Context, in *FaceRecognitionRequest, opts ...grpc.CallOption) (*FaceRecognitionResponse, error)
		// TfClassification
		TfClassification(ctx context.Context, in *TfClassificationRequest, opts ...grpc.CallOption) (*TfClassificationResponse, error)
		// CaffeClassification
		CaffeClassification(ctx context.Context, in *CaffeClassificationRequest, opts ...grpc.CallOption) (*CaffeClassificationResponse, error)
		// QueryFaceLibrary
		QueryFaceLibrary(ctx context.Context, in *QueryFaceLibraryRequest, opts ...grpc.CallOption) (*QueryFaceLibraryResponse, error)
		// ModifyFaceName
		ModifyFaceName(ctx context.Context, in *ModifyFaceNameRequest, opts ...grpc.CallOption) (*ModifyFaceNameResponse, error)
		// ModifyFaceType
		ModifyFaceType(ctx context.Context, in *ModifyFaceTypeRequest, opts ...grpc.CallOption) (*ModifyFaceTypeResponse, error)
		// FuzzySearch
		ImageClarity(ctx context.Context, in *ImageClarityRequest, opts ...grpc.CallOption) (*ImageClarityResponse, error)
	}

	defaultAiService struct {
		cli zrpc.Client
	}
)

func NewAiService(cli zrpc.Client) AiService {
	return &defaultAiService{
		cli: cli,
	}
}

// FaceRecognition
func (m *defaultAiService) FaceRecognition(ctx context.Context, in *FaceRecognitionRequest, opts ...grpc.CallOption) (*FaceRecognitionResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.FaceRecognition(ctx, in, opts...)
}

// TfClassification
func (m *defaultAiService) TfClassification(ctx context.Context, in *TfClassificationRequest, opts ...grpc.CallOption) (*TfClassificationResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.TfClassification(ctx, in, opts...)
}

// CaffeClassification
func (m *defaultAiService) CaffeClassification(ctx context.Context, in *CaffeClassificationRequest, opts ...grpc.CallOption) (*CaffeClassificationResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.CaffeClassification(ctx, in, opts...)
}

// QueryFaceLibrary
func (m *defaultAiService) QueryFaceLibrary(ctx context.Context, in *QueryFaceLibraryRequest, opts ...grpc.CallOption) (*QueryFaceLibraryResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.QueryFaceLibrary(ctx, in, opts...)
}

// ModifyFaceName
func (m *defaultAiService) ModifyFaceName(ctx context.Context, in *ModifyFaceNameRequest, opts ...grpc.CallOption) (*ModifyFaceNameResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.ModifyFaceName(ctx, in, opts...)
}

// ModifyFaceType
func (m *defaultAiService) ModifyFaceType(ctx context.Context, in *ModifyFaceTypeRequest, opts ...grpc.CallOption) (*ModifyFaceTypeResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.ModifyFaceType(ctx, in, opts...)
}

// FuzzySearch
func (m *defaultAiService) ImageClarity(ctx context.Context, in *ImageClarityRequest, opts ...grpc.CallOption) (*ImageClarityResponse, error) {
	client := pb.NewAiServiceClient(m.cli.Conn())
	return client.ImageClarity(ctx, in, opts...)
}
